main:
  - name: Home
    url: '#'
    weight: 10
  - name: Team
    url: '#people'
    weight: 20
  - name: Editions
    url: '#editions'
    weight: 30
  - name: Projects
    url: '#projects'
    weight: 40
  - name: Contact
    url: '#contact'
    weight: 80

